services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: polytech
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  mongodb:
    image: mongo:7
    ports:
      - "27017:27017"

  erasmumu:
    build: ./erasmumu
    ports:
      - "3002:3002"
    environment:
      MONGO_URL: mongodb://mongodb:27017/erasmumu
    depends_on:
      - mongodb

  polytech:
    build: ./polytech
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/polytech
      ERASMUMU_URL: http://erasmumu:3002
    depends_on:
      - postgres
      - erasmumu
